### ISSUE TITLE
Exception in thread Thread-XX (vision_mode)

### ISSUE THREAD

**Issue by NoNameTrademark** [aeon0/d4lf#129]
I get this error sometimes which removes the overlay from the vision mods script (in 3.4.0):

Exception in thread Thread-20 (vision_mode):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "scripts\vision_mode.py", line 144, in vision_mode
  File "item\descr\read_descr.py", line 51, in read_descr
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-24 (vision_mode):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "scripts\vision_mode.py", line 144, in vision_mode
  File "item\descr\read_descr.py", line 77, in read_descr
  File "item\descr\find_affixes.py", line 53, in find_affixes
TypeError: object of type 'NoneType' has no len()

**Comment by aeon0** [comment]
should be fixed with 3.4.1
