### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by takenek** [aeon0/d4lf#142]
[3.4.2 2024-01-08 13:02:34,295] INFO       Items: 9 in Char_Inventory
Exception in thread Thread-5 (_wrapper_run_loot_filter):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "overlay.py", line 190, in _wrapper_run_loot_filter
  File "loot_filter.py", line 108, in run_loot_filter
  File "loot_filter.py", line 50, in check_items
  File "item\descr\read_descr.py", line 92, in read_descr
  File "item\descr\find_aspect.py", line 30, in find_aspect
  File "item\descr\texture.py", line 69, in find_aspect_search_area
  File "numpy\core\_methods.py", line 41, in _amax
ValueError: zero-size array to reduction operation maximum which has no identity

On this item:
![image](https://github.com/aeon0/d4lf/assets/4953735/4b970e89-c855-4aed-85f8-1afd4f95130c)
![image](https://github.com/aeon0/d4lf/assets/4953735/61ced3ad-8580-4a64-b772-350713b58735)

**Comment by aeon0** [comment]
Fixed the exception on main branch already. But it will then not show up as detected. I assume the aspect text is hidden by "scroll down" icon. Setting font-size to small can reduce the occurances of this.

**Comment by CaffeineBytes** [comment]
> Fixed the exception on main branch already. But it will then not show up as detected. I assume the aspect text is hidden by "scroll down" icon. Setting font-size to small can reduce the occurances of this.

Can you link me to the commit that fixed this? I've seen this with sorcerers' affixes and am wondering if the same fix could be applied to it to prevent crashing. I was just thinking a try-catch and returning None for the affixes in the code.
![image](https://github.com/aeon0/d4lf/assets/25422793/5aedd103-2964-422d-89b1-087b1e787282)

**Comment by aeon0** [comment]
Hmm, somehow the image provided to the ocr function is empty. I will catch that and add a warning as you suggested!

**Comment by aeon0** [comment]
should be ok with 4.0.1
