### ISSUE TITLE
Error during diablo.trade fetching 

### ISSUE THREAD

**Issue by brunosw** [aeon0/d4lf#340]
Fetched 1000 listings
Failed to validate profile. Dumping data for debugging.
Traceback (most recent call last):
  File "gui\importer\diablo_trade.py", line 103, in import_diablo_trade
  File "gui\importer\diablo_trade.py", line 168, in _create_filters_from_items
TypeError: '<' not supported between instances of 'list' and 'float'
An error occurred while importing. Retrying...
Traceback (most recent call last):
  File "gui\importer\diablo_trade.py", line 103, in import_diablo_trade
  File "gui\importer\diablo_trade.py", line 168, in _create_filters_from_items
TypeError: '<' not supported between instances of 'list' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\importer\common.py", line 150, in wrapper
  File "gui\importer\diablo_trade.py", line 110, in import_diablo_trade
  File "json\__init__.py", line 179, in dump
  File "json\encoder.py", line 430, in _iterencode
  File "json\encoder.py", line 326, in _iterencode_list
  File "json\encoder.py", line 439, in _iterencode
  File "json\encoder.py", line 180, in default
TypeError: Object of type _Listing is not JSON serializable
Start fetching listings
Fetched 20 listings
Fetched 40 listings

**Comment by chrisoro** [comment]
Which version are you using? 5.6.4 should have fixed this.

If not, provide the exact filter that you are running

**Comment by brunosw** [comment]
I was not using the last version. It's solved, thanks!
