### ISSUE TITLE
Unhandled exception caused by thread (KeyError: 'ItemPower')

### ISSUE THREAD

**Issue by fredrikscode** [aeon0/d4lf#376]
v5.7.10
Highest possible graphics settings in-game
No HDR
Tried with advanced tooltip information on/off
Tried with advanced tooltip compare on/off

**Error log**
```
 Unhandled exception caused by thread 'Thread-14 (_wrapper_run_loot_interaction_method)'
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "overlay.py", line 190, in _wrapper_run_loot_interaction_method
  File "loot_filter.py", line 168, in run_loot_filter
  File "loot_filter.py", line 73, in check_items
  File "item\descr\read_descr.py", line 40, in read_descr
  File "item\descr\item_type.py", line 48, in read_item_type
  File "item\descr\item_type.py", line 65, in _find_item_power_and_type
KeyError: 'ItemPower' 
```

This happens on any legendary item I have in my inventory of various item power levels or qualities.

Any suggestions? :)

**Comment by chrisoro** [comment]
cleanup. if it still happens on newest version please reopen
