### ISSUE TITLE
Error importing Spiritborn build

### ISSUE THREAD

**Issue by n4ks** [aeon0/d4lf#382]
So, I'm trying to import this build.
https://maxroll.gg/d4/build-guides/stinger-spiritborn-leveling-guide

And I get this error when I click on the generate button.

```
2024-10-10 | 01:17:47.667 | MainThread | INFO | src.logger:102 | Running version v5.8.1
2024-10-10 | 01:17:50.899 | maxroll | INFO | src.gui.importer.maxroll:34 | Loading https://maxroll.gg/d4/build-guides/stinger-spiritborn-leveling-guide
2024-10-10 | 01:17:51.513 | maxroll | ERROR | src.gui.importer.common:158 | An error occurred while importing. Retrying...
Traceback (most recent call last):
  File "gui\importer\common.py", line 153, in wrapper
  File "gui\importer\maxroll.py", line 36, in import_maxroll
  File "gui\importer\maxroll.py", line 233, in _extract_planner_url_and_id_from_guide
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-10-10 | 01:17:51.515 | maxroll | INFO | src.gui.importer.maxroll:34 | Loading https://maxroll.gg/d4/build-guides/stinger-spiritborn-leveling-guide
2024-10-10 | 01:17:52.091 | maxroll | ERROR | src.gui.importer.common:158 | An error occurred while importing. Retrying...
Traceback (most recent call last):
  File "gui\importer\common.py", line 153, in wrapper
  File "gui\importer\maxroll.py", line 36, in import_maxroll
  File "gui\importer\maxroll.py", line 233, in _extract_planner_url_and_id_from_guide
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-10-10 | 01:17:52.093 | maxroll | INFO | src.gui.importer.maxroll:34 | Loading https://maxroll.gg/d4/build-guides/stinger-spiritborn-leveling-guide
2024-10-10 | 01:17:52.828 | maxroll | ERROR | src.gui.importer.common:158 | An error occurred while importing. Retrying...
Traceback (most recent call last):
  File "gui\importer\common.py", line 153, in wrapper
  File "gui\importer\maxroll.py", line 36, in import_maxroll
  File "gui\importer\maxroll.py", line 233, in _extract_planner_url_and_id_from_guide
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-10-10 | 01:17:52.829 | maxroll | INFO | src.gui.importer.maxroll:34 | Loading https://maxroll.gg/d4/build-guides/stinger-spiritborn-leveling-guide
2024-10-10 | 01:17:53.423 | maxroll | ERROR | src.gui.importer.common:158 | An error occurred while importing. Retrying...
Traceback (most recent call last):
  File "gui\importer\common.py", line 153, in wrapper
  File "gui\importer\maxroll.py", line 36, in import_maxroll
  File "gui\importer\maxroll.py", line 233, in _extract_planner_url_and_id_from_guide
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-10-10 | 01:17:53.425 | maxroll | INFO | src.gui.importer.maxroll:34 | Loading https://maxroll.gg/d4/build-guides/stinger-spiritborn-leveling-guide
2024-10-10 | 01:17:54.014 | maxroll | ERROR | src.gui.importer.common:158 | An error occurred while importing. Retrying...
Traceback (most recent call last):
  File "gui\importer\common.py", line 153, in wrapper
  File "gui\importer\maxroll.py", line 36, in import_maxroll
  File "gui\importer\maxroll.py", line 233, in _extract_planner_url_and_id_from_guide
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by TheOne320** [comment]
Some here. I tried an endgame build:
https://maxroll.gg/d4/build-guides/quill-volley-spiritborn-guide

and the same thing happens.

**Comment by n4ks** [comment]
Yeah, it works perfectly now. Thank you guys!
